apiVersion: v1
kind: Service
metadata:
  name: dev-kube-state-metrics-external
  namespace: monitoring
  labels:
    app.kubernetes.io/name: dev-kube-state-metrics-external
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dev-kube-state-metrics-external
  namespace: monitoring
subsets:
- addresses:
  - ip: "172.18.0.13"  # Your dev cluster IP from the ExternalName service
  ports:
  - name: http-metrics
    port: 30080
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-kube-state-metrics
  namespace: monitoring
  labels:
    app: kube-state-metrics
    release: kube-prometheus-stack
spec:
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: dev-kube-state-metrics-external